<?php

/**
 * @file
 * Install, uninstall, and requirements operations.
 */

/**
 * Move Masked Input settings from variables to config.
 */
function masked_input_update_1000() {
  // Migrate variables to config.
  $config = config('masked_input.settings');
  $config->set('input_definitions', update_variable_get('masked_input_definitions', array()));
  $config->save();

  // Delete variables.
  update_variable_del('masked_input_definitions');
}
